name: Update Rutherford Count

on: 
  workflow_dispatch:
    inputs:
      count:
        description: 'Count of new cases for today'     
        required: true
        
jobs:
  addData:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Update Rutherford Count
      run: ./.github/workflows/add_rutherford_data.bash ${{ github.event.inputs.count }}
