name: Update Data

on:
  workflow_run:
    workflows: ["Update Rutherford Count"]
    types: 
      - completed
  workflow_dispatch:
  push:
    paths: 
      - '**.py'
      - 'data/csv/rutherford_data.csv'
  schedule:
    - cron: '42 * * * *'

jobs:
  # Build and cache the docker image from the repo.
  update_data_and_charts:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
        
    - name: Build docker image
      run: docker build . -t rutherford-covid-image
        
    - name: Update data and charts
      run: ./.github/workflows/update_data.bash
