name: Update Data

on: [workflow_dispatch]

jobs:
  # Get data from sources and store in repo.
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Fetch data
        run: cd data && go run *.go

