name: Update Data

on:
  workflow_dispatch:
  push:
    paths: 
      - '**.py'
  schedule:
    - cron: '2,22,42 * * * *'

jobs:
  # Build and cache the docker image from the repo.
  update_data_and_charts:
    runs-on: ubuntu-20.04
    steps:
    - name: Setup git environment
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com

    - name: Checkout Codebase
      uses: actions/checkout@v2

    - name: Setup Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.5'

    - name: Setup Node.js environment
      uses: actions/setup-node@v1
      with:
        node-version: '14.15.1'
    
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y curl jq r-base

    - name: Install Python requirements
      run: pip install -r requirements.txt

    - name: Install SVGO
      run: npm install -g svgo

    - name: Fetch data and update graphs
      run: ./.github/workflows/update_data.bash
