name: Update Data

on:
  repository_dispatch:
    types: update-data
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  # Get data from sources and store in repo.
  update_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Write time
        run: date

      - name: Fetch data
        run: cd data && go run *.go

      - name: Update charts
        run: |
          ./run.bash

      - name: Commit data changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update data."
          git push

