name: Update Data

on:
  workflow_run:
    workflows: ["Update Rutherford Count"]
    types: 
      - completed
  workflow_dispatch:

jobs:
  update_data_and_charts:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
        
    - name: Update data and charts
      run: ./.github/workflows/update_data.bash
