name: Update Data

on:
  repository_dispatch:
    types: update-data
  workflow_dispatch:
  push:
    paths: 
      - 'process_covid_data.py'
  schedule:
    - cron: '2,22,42 * * * *'

jobs:
  # Get data from sources and store in repo.
  update_data:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Update data and charts
        run: ./.github/workflows/update_data.sh
