name: Update Data

on: [workflow_dispatch]

jobs:
  # Get data from sources and store in repo.
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Fetch data
        run: cd data && go run *.go

      - name: Commit data changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update data."
          git push

